name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # (Optional) ensure a fixed Python version
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: snok/install-poetry@v1

      # Install only dependencies (main + dev tools), skip the project itself
      - run: poetry install --no-root --with dev

      # Linting & formatting checks
      - run: poetry run ruff .
      - run: poetry run isort --check .
      - run: poetry run black --check .